USE DWSchemaSchool;
GO

CREATE TABLE Date(
	DateID INT IDENTITY(1,1) PRIMARY KEY,
	Date DATE NOT NULL,
	Year INT NOT NULL,
	Month VARCHAR(20) NOT NULL,
	MonthNumber INT NOT NULL,
	Day INT NOT NULL
);

CREATE TABLE Time(
	TimeID INT IDENTITY(1,1) PRIMARY KEY,
	Hour INT NOT NULL,
	TimeOfDay VARCHAR(20) NOT NULL
);

CREATE TABLE Exam(
	ExamID INT IDENTITY(1,1) PRIMARY KEY,
	Type VARCHAR(15) NOT NULL,
	DurationCategory VARCHAR(10) NOT NULL,
	ExamTimeCategory VARCHAR(10) NOT NULL
);

CREATE TABLE Class(
	ClassID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(5) NOT NULL,
	Specialization VARCHAR(25) NOT NULL,
	Level VARCHAR(25) NOT NULL
);

CREATE TABLE Students(
	StudentID INT IDENTITY(1,1) PRIMARY KEY,
	StudentIndex INT NOT NULL,
	SName VARCHAR(30) NOT NULL,
	SSurname VARCHAR(30) NOT NULL,
	AgeCategory VARCHAR(5) NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	City VARCHAR(30) NOT NULL,
	District VARCHAR(30) NOT NULL,
	IsCurrent BIT NOT NULL
);

CREATE TABLE Teachers(
	TeacherID INT IDENTITY(1,1) PRIMARY KEY,
	TeacherIndex INT NOT NULL,
	TName VARCHAR(30) NOT NULL,
	TSurname VARCHAR(30) NOT NULL,
	Title VARCHAR(20) NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	AgeCategory VARCHAR(5) NOT NULL,
	City VARCHAR(30) NOT NULL,
	District VARCHAR(30) NOT NULL,
	IsCurrent BIT NOT NULL
);

CREATE TABLE Grading(
	ExamID INT,
	StudentID INT,
	TeacherID INT,
	SupervisorID INT,
	TimeID INT,
	DateID INT,
	ClassID INT,
	Grade FLOAT NOT NULL,
	Satisfaction INT NOT NULL,
	WritingTime INT NOT NULL,
	PRIMARY KEY(ExamID, StudentID, TeacherID,
	SupervisorID, TimeID, DateID, ClassID),
	FOREIGN KEY(ExamID) REFERENCES Exam(ExamID),
	FOREIGN KEY(StudentID) REFERENCES Students(StudentID),
	FOREIGN KEY(TeacherID) REFERENCES Teachers(TeacherID),
	FOREIGN KEY(SupervisorID) REFERENCES Teachers(TeacherID),
	FOREIGN KEY(TimeID) REFERENCES Time(TimeID),
	FOREIGN KEY(DateID) REFERENCES Date(DateID),
	FOREIGN KEY(ClassID) REFERENCES Class(ClassID)
);
